apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp-recreate


spec:
  strategy:
    type: Recreate
    
  selector:
    matchLabels:
      app: frontend-pod


  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod
        type: frontend

    spec:
      containers:
        - name: frontend-container
          image: nginx:1.20

  replicas: 6
