apiVersion: v1
kind: Pod


metadata:
  name: mysql-pod
  labels:
    app: mysql-app
    env: production

spec:
  
  containers:
    - name: mysql-container
      image: mysql:latest
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"

        requests:
          memory: 256Mi
          cpu: "0.2"

      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      
        - name: MYSQL_DATABASE
          value: "pod_db"

    