apiVersion: apps/v1
kind: Deployment

metadata:
  name: webapp-deployment

spec:
  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp
        
    spec:
      containers:
        - name: webapp-container
          image: nginx
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"

            requests:
              memory: 256Mi
              cpu: "0.2"


  replicas: 3